services:
  backend:
    build: ./backend
    container_name: skills-hub-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/courses.db:/app/courses.db
    environment:
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=http://localhost:3000

  frontend:
    build: ./frontend
    container_name: skills-hub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=production 